/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CandidatesIndexRouteImport } from './routes/candidates/index'
import { Route as FormCandidateIdRouteImport } from './routes/form/$candidateId'
import { Route as DemoQueryFlowRouteImport } from './routes/demo/query-flow'
import { Route as DemoClassFuncRouteImport } from './routes/demo/class-func'
import { Route as CandidatesCandidateIdRouteImport } from './routes/candidates/$candidateId'
import { Route as CandidatesCandidateIdEditRouteImport } from './routes/candidates.$candidateId.edit'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesIndexRoute = CandidatesIndexRouteImport.update({
  id: '/candidates/',
  path: '/candidates/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormCandidateIdRoute = FormCandidateIdRouteImport.update({
  id: '/form/$candidateId',
  path: '/form/$candidateId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoQueryFlowRoute = DemoQueryFlowRouteImport.update({
  id: '/demo/query-flow',
  path: '/demo/query-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoClassFuncRoute = DemoClassFuncRouteImport.update({
  id: '/demo/class-func',
  path: '/demo/class-func',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesCandidateIdRoute = CandidatesCandidateIdRouteImport.update({
  id: '/candidates/$candidateId',
  path: '/candidates/$candidateId',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesCandidateIdEditRoute =
  CandidatesCandidateIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => CandidatesCandidateIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/candidates/$candidateId': typeof CandidatesCandidateIdRouteWithChildren
  '/demo/class-func': typeof DemoClassFuncRoute
  '/demo/query-flow': typeof DemoQueryFlowRoute
  '/form/$candidateId': typeof FormCandidateIdRoute
  '/candidates/': typeof CandidatesIndexRoute
  '/candidates/$candidateId/edit': typeof CandidatesCandidateIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/candidates/$candidateId': typeof CandidatesCandidateIdRouteWithChildren
  '/demo/class-func': typeof DemoClassFuncRoute
  '/demo/query-flow': typeof DemoQueryFlowRoute
  '/form/$candidateId': typeof FormCandidateIdRoute
  '/candidates': typeof CandidatesIndexRoute
  '/candidates/$candidateId/edit': typeof CandidatesCandidateIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/candidates/$candidateId': typeof CandidatesCandidateIdRouteWithChildren
  '/demo/class-func': typeof DemoClassFuncRoute
  '/demo/query-flow': typeof DemoQueryFlowRoute
  '/form/$candidateId': typeof FormCandidateIdRoute
  '/candidates/': typeof CandidatesIndexRoute
  '/candidates/$candidateId/edit': typeof CandidatesCandidateIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/candidates/$candidateId'
    | '/demo/class-func'
    | '/demo/query-flow'
    | '/form/$candidateId'
    | '/candidates/'
    | '/candidates/$candidateId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/candidates/$candidateId'
    | '/demo/class-func'
    | '/demo/query-flow'
    | '/form/$candidateId'
    | '/candidates'
    | '/candidates/$candidateId/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/candidates/$candidateId'
    | '/demo/class-func'
    | '/demo/query-flow'
    | '/form/$candidateId'
    | '/candidates/'
    | '/candidates/$candidateId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CandidatesCandidateIdRoute: typeof CandidatesCandidateIdRouteWithChildren
  DemoClassFuncRoute: typeof DemoClassFuncRoute
  DemoQueryFlowRoute: typeof DemoQueryFlowRoute
  FormCandidateIdRoute: typeof FormCandidateIdRoute
  CandidatesIndexRoute: typeof CandidatesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates/': {
      id: '/candidates/'
      path: '/candidates'
      fullPath: '/candidates/'
      preLoaderRoute: typeof CandidatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form/$candidateId': {
      id: '/form/$candidateId'
      path: '/form/$candidateId'
      fullPath: '/form/$candidateId'
      preLoaderRoute: typeof FormCandidateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/query-flow': {
      id: '/demo/query-flow'
      path: '/demo/query-flow'
      fullPath: '/demo/query-flow'
      preLoaderRoute: typeof DemoQueryFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/class-func': {
      id: '/demo/class-func'
      path: '/demo/class-func'
      fullPath: '/demo/class-func'
      preLoaderRoute: typeof DemoClassFuncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates/$candidateId': {
      id: '/candidates/$candidateId'
      path: '/candidates/$candidateId'
      fullPath: '/candidates/$candidateId'
      preLoaderRoute: typeof CandidatesCandidateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates/$candidateId/edit': {
      id: '/candidates/$candidateId/edit'
      path: '/edit'
      fullPath: '/candidates/$candidateId/edit'
      preLoaderRoute: typeof CandidatesCandidateIdEditRouteImport
      parentRoute: typeof CandidatesCandidateIdRoute
    }
  }
}

interface CandidatesCandidateIdRouteChildren {
  CandidatesCandidateIdEditRoute: typeof CandidatesCandidateIdEditRoute
}

const CandidatesCandidateIdRouteChildren: CandidatesCandidateIdRouteChildren = {
  CandidatesCandidateIdEditRoute: CandidatesCandidateIdEditRoute,
}

const CandidatesCandidateIdRouteWithChildren =
  CandidatesCandidateIdRoute._addFileChildren(
    CandidatesCandidateIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CandidatesCandidateIdRoute: CandidatesCandidateIdRouteWithChildren,
  DemoClassFuncRoute: DemoClassFuncRoute,
  DemoQueryFlowRoute: DemoQueryFlowRoute,
  FormCandidateIdRoute: FormCandidateIdRoute,
  CandidatesIndexRoute: CandidatesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
